theme = "stack"
baseURL = "https://luckysynapse.lpillay.workers.dev/"
languageCode = "en-us"
title = "Lucky Synapse"

[params]
  mainSections = ["tech", "personal"]
  rssFullContent = true

  [params.footer]
    since = 2026

  [params.dateFormat]
    published = ":date_full"
    lastUpdated = ":date_full"

  [params.sidebar]
    compact = false

  [params.article]
    toc = true
    readingTime = true
    headingAnchor = true

    [params.article.list]
      showTags = true

    [params.article.license]
      enabled = false

  [params.colorScheme]
    toggle = true
    default = "auto"

  [params.comments]
    enabled = false

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "monokai"
  [markup.goldmark.renderer]
    unsafe = true

[[menu.main]]
  name = "Tech"
  pageRef = "/tech"
  weight = 1

[[menu.main]]
  name = "Personal"
  pageRef = "/personal"
  weight = 2

[[menu.main]]
  name = "Tags"
  pageRef = "/tags"
  weight = 3
